name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install casacore
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: casacore-dev
        version: 1.0
    - name: casacore info
      run: |
        apt info casacore-dev
        dpkg -L casacore-dev
    - name: validate
      run: |
        make validate ARGS="-i 100 -T 16 -B 526 -C 128"
    - name: bench
      run: |
        make bench ARGS="-i 100 -T 16 -B 526 -C 128"
      # env:
      #   LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/
      #   LDFLAGS: -L/usr/lib/x86_64-linux-gnu -lcasa_tables -lcasa_casa -lcasa_ms